package com.billcom.apc.generatedSOAP.PBI_CMS.APCManager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-03-18T12:52:04.485+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://manager.ws.apc.billcom.com/", name = "APCManager")
@XmlSeeAlso({ObjectFactory.class})
public interface APCManager {

    @WebMethod
    @RequestWrapper(localName = "contractHasMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.ContractHasMigration")
    @ResponseWrapper(localName = "contractHasMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.ContractHasMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyMigrationResponse contractHasMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyMigrationRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendEmailMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.SendEmailMigration")
    @ResponseWrapper(localName = "sendEmailMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.SendEmailMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.SendEmailResponse sendEmailMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.SendMailRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getContractHistory", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetContractHistory")
    @ResponseWrapper(localName = "getContractHistoryResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetContractHistoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationsResponse getContractHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceBscs", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceBscs")
    @ResponseWrapper(localName = "adjustBalanceBscsResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceBscsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceResponse adjustBalanceBscs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMigrationOrderParentProcess", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationOrderParentProcess")
    @ResponseWrapper(localName = "getMigrationOrderParentProcessResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationOrderParentProcessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationOrderParentResponse getMigrationOrderParentProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.OrderRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "percistMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.PercistMigration")
    @ResponseWrapper(localName = "percistMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.PercistMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.PercistMigrationOrderResponse percistMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.PercistMigrationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getNBofmigrationexecutedforcontract", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetNBofmigrationexecutedforcontract")
    @ResponseWrapper(localName = "getNBofmigrationexecutedforcontractResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetNBofmigrationexecutedforcontractResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.NbreMigrationExecutedResponse getNBofmigrationexecutedforcontract(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.NbreMigrationExecutedRequest arg0
    ) throws InvalidInputException_Exception, ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateMigration")
    @ResponseWrapper(localName = "updateMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateMigrationOrderResponse updateMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateMigrationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.DeleteMigration")
    @ResponseWrapper(localName = "deleteMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.DeleteMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.DeleteMigrationOrderResponse deleteMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.OrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMigrationOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationOrder")
    @ResponseWrapper(localName = "getMigrationOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationResponse getMigrationOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.OrderRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getListOrderId", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetListOrderId")
    @ResponseWrapper(localName = "getListOrderIdResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetListOrderIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Long> getListOrderId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMigrationList", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationList")
    @ResponseWrapper(localName = "getMigrationListResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationsResponse getMigrationList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetMigrationsRequest arg0
    ) throws InvalidInputException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateCoIdMigrationOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateCoIdMigrationOrder")
    @ResponseWrapper(localName = "updateCoIdMigrationOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.UpdateCoIdMigrationOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean updateCoIdMigrationOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.math.BigInteger arg2
    ) throws InvalidInputException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceMigration")
    @ResponseWrapper(localName = "adjustBalanceMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceResponse adjustBalanceMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDetailsOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetDetailsOrder")
    @ResponseWrapper(localName = "getDetailsOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetDetailsOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetOrderResponse getDetailsOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.OrderRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verifyFunctionalEligebility", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyFunctionalEligebility")
    @ResponseWrapper(localName = "verifyFunctionalEligebilityResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyFunctionalEligebilityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyEligebilityResponse verifyFunctionalEligebility(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyMigrationRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceIn", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceIn")
    @ResponseWrapper(localName = "adjustBalanceInResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceResponse adjustBalanceIn(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEligibileContractForMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetEligibileContractForMigration")
    @ResponseWrapper(localName = "getEligibileContractForMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetEligibileContractForMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetEligibleContractForMigrationResponse getEligibileContractForMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.GetEligibileContractForMigrationRequest arg0
    ) throws InvalidInputException_Exception, NotFoundException_Exception, ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verifyTechnicalEligibility", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyTechnicalEligibility")
    @ResponseWrapper(localName = "verifyTechnicalEligibilityResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyTechnicalEligibilityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyEligebilityResponse verifyTechnicalEligibility(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.APCManager.VerifyMigrationRequest arg0
    );
}
