package com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-08-20T10:22:32.937+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://manager.ws.resiliation.billcom.com/", name = "ResiliationManager")
@XmlSeeAlso({ObjectFactory.class})
public interface ResiliationManager {

    @WebMethod
    @RequestWrapper(localName = "getListOrdersForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetListOrdersForResiliation")
    @ResponseWrapper(localName = "getListOrdersForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetListOrdersForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetListOrdersResiliationResponse getListOrdersForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetListOrdersRequest arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getContratsForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetContratsForResiliation")
    @ResponseWrapper(localName = "getContratsForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetContratsForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetContractsResponse getContratsForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetOrderDetailsRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getOrderDetailsForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetOrderDetailsForResiliation")
    @ResponseWrapper(localName = "getOrderDetailsForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetOrderDetailsForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetOrderDetailsResponse getOrderDetailsForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetOrderDetailsRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateResiliationProcessParent", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationProcessParent")
    @ResponseWrapper(localName = "updateResiliationProcessParentResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationProcessParentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationOrderResponse updateResiliationProcessParent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getContractDetailsForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetContractDetailsForResiliation")
    @ResponseWrapper(localName = "getContractDetailsForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetContractDetailsForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetListOrdersResiliationResponse getContractDetailsForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getEligibleContratForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetEligibleContratForResiliation")
    @ResponseWrapper(localName = "getEligibleContratForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetEligibleContratForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetEligibleContratResponse getEligibleContratForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.GetEligibleContratRequest arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "setContractOrderIdForResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.SetContractOrderIdForResiliation")
    @ResponseWrapper(localName = "setContractOrderIdForResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.SetContractOrderIdForResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.SetContractOrderIdResponse setContractOrderIdForResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.SetContractOrderIdRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "percisteResiliation", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.PercisteResiliation")
    @ResponseWrapper(localName = "percisteResiliationResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.PercisteResiliationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.PercistResiliationOrderResponse percisteResiliation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.PercistResiliationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateResiliationSubProcess", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationSubProcess")
    @ResponseWrapper(localName = "updateResiliationSubProcessResponse", targetNamespace = "http://manager.ws.resiliation.billcom.com/", className = "com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationSubProcessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationOrderResponse updateResiliationSubProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.generatedSOAP.PBI_CMS.resiliationManager.UpdateResiliationOrderRequest arg0
    );
}
