package com.billcom.apc.generatedSOAP.BalanceManagerV2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-03-18T12:52:04.142+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "BalanceManagerV2Service", 
                  wsdlLocation = "http://192.168.1.11:8080/testMockServer/mockBalanceManagerV2SoapBinding?WSDL",
                  targetNamespace = "http://v2.manager.ws.lucent.alcatel.com") 
public class BalanceManagerV2Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://v2.manager.ws.lucent.alcatel.com", "BalanceManagerV2Service");
    public final static QName BalanceManagerV2 = new QName("http://v2.manager.ws.lucent.alcatel.com", "BalanceManagerV2");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.11:8080/testMockServer/mockBalanceManagerV2SoapBinding?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BalanceManagerV2Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.11:8080/testMockServer/mockBalanceManagerV2SoapBinding?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public BalanceManagerV2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BalanceManagerV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceManagerV2Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BalanceManagerV2Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BalanceManagerV2Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BalanceManagerV2Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BalanceManagerV2
     */
    @WebEndpoint(name = "BalanceManagerV2")
    public BalanceManagerV2 getBalanceManagerV2() {
        return super.getPort(BalanceManagerV2, BalanceManagerV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceManagerV2
     */
    @WebEndpoint(name = "BalanceManagerV2")
    public BalanceManagerV2 getBalanceManagerV2(WebServiceFeature... features) {
        return super.getPort(BalanceManagerV2, BalanceManagerV2.class, features);
    }

}
