package com.billcom.apc.generatedSOAP.BalanceManagerV2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-03-18T12:52:04.134+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", name = "BalanceManagerV2")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BalanceManagerV2 {

    @WebMethod
    @WebResult(name = "testRefillMainBalanceReturn", targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", partName = "testRefillMainBalanceReturn")
    public TestRefillMainBalanceBeanOutput testRefillMainBalance(
        @WebParam(partName = "testRefillMainBalanceBeanInput", name = "testRefillMainBalanceBeanInput")
        TestRefillMainBalanceBeanInput testRefillMainBalanceBeanInput
    );

    @WebMethod
    @WebResult(name = "refillMainBalanceReturn", targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", partName = "refillMainBalanceReturn")
    public OperationResponseV2 refillMainBalance(
        @WebParam(partName = "refillMainBalanceBeanInput", name = "refillMainBalanceBeanInput")
        RefillMainBalanceBeanInputV2 refillMainBalanceBeanInput
    );

    @WebMethod
    @WebResult(name = "getBalanceAndDateReturn", targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", partName = "getBalanceAndDateReturn")
    public GetBalanceAndDateBeanOutputV2 getBalanceAndDate(
        @WebParam(partName = "getBalanceAndDateBeanInput", name = "getBalanceAndDateBeanInput")
        GetBalanceAndDateBeanInputV2 getBalanceAndDateBeanInput
    );

    @WebMethod
    @WebResult(name = "buyOptionsReturn", targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", partName = "buyOptionsReturn")
    public OperationResponseV2 buyOptions(
        @WebParam(partName = "buyOptionBeanInput", name = "buyOptionBeanInput")
        BuyOptionBeanInputV2 buyOptionBeanInput
    );

    @WebMethod
    @WebResult(name = "testBuyOptionReturn", targetNamespace = "http://v2.manager.ws.lucent.alcatel.com", partName = "testBuyOptionReturn")
    public TestBuyOptionBeanOutput testBuyOption(
        @WebParam(partName = "testBuyOptionBeanInput", name = "testBuyOptionBeanInput")
        TestBuyOptionBeanInput testBuyOptionBeanInput
    );
}
