/**
 * APCHandling.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.billcom.apc.generatedSOAP.bscs.apcHandling;

public interface APCHandling extends java.rmi.Remote {
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetTypeResponse getType(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetTypeRequest getTypeRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCategoryResponse getMigrationCategory(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCategoryRequest getMigrationCategoryRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetContractFromMsisdnResponse getContractFromMsisdn(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCoIdRequest getContractFromMsisdnRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.ActivateServiceParamterResponse activateAndSetParameterServices(com.billcom.apc.generatedSOAP.bscs.apcHandling.ActivateServiceParamter activateAndSetParameterServicesRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse activateOnHoldService(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest coIdRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMsisdnFromCoIdResponse getMsisdnFromCoId(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getMsisdnFromCoIdRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.HasPendingRequestResponse hasPendingRequest(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest hasPendingrequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.DifferentServiceTemplateResponse getDifferentsServiceTemplate(com.billcom.apc.generatedSOAP.bscs.apcHandling.DifferentServiceTemplateRequest getDifferentsServiceTemplateRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationDateResponse updateOperationDate(com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationDateRequest updateOperationDateRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetContractListForCustomerResponse getContractListForCustomer(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetContractListForCustomerRequest getContractListeForCustomerRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.CalculateAccelerationResponse calculateAcceleration(com.billcom.apc.generatedSOAP.bscs.apcHandling.CalculateAccelerationRequest calculateAccelerationRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetEngagementStatusResponse getEngagementStatus(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getEngagementStatusRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.DesactivateServicesResponse desactivateServices(com.billcom.apc.generatedSOAP.bscs.apcHandling.DesactivateServicesRequest desactivateServicesRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.EligibilityTemplateResponse getEligebilityTemplate(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getEligebilityTemplateRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.BalanceResponse getBalancesContractHist(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetBalancesRequest getBalancesRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse insertBalanceHist(com.billcom.apc.generatedSOAP.bscs.apcHandling.BalanceHistRequest insertBalanceHistRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetOptionalServicesResponse getOptionalServices(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetServiceRequest getOptionalServicesRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse desactivateContract(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest desactivateContractRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse insertFafNumberHist(com.billcom.apc.generatedSOAP.bscs.apcHandling.ApcFafNumberHistRequest apcFafNumberHistRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.MontantFactureResponse getMontantFacture(com.billcom.apc.generatedSOAP.bscs.apcHandling.CustomerRequest getMontantFactureRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMigrationIntervalResponse getMigrationInterval(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMigrationIntervalRequest getMigrationIntervalRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCustomerStatisticsResponse getCustomerStatistics(com.billcom.apc.generatedSOAP.bscs.apcHandling.CustomerRequest getCustomerStatisticsRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCUGResponse getCUG(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getCUGRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.NbreMigrationResponse getNbreMigration(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getNbreMigrationRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OCCResponse setOCC(com.billcom.apc.generatedSOAP.bscs.apcHandling.OCCRequest setOCCRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetOffreResponse getOffreSource(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetOffreRequest getOffreSourceRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.ChangeRatePlanResponse changeRateplan(com.billcom.apc.generatedSOAP.bscs.apcHandling.ChangeRatePlanRequest changeRatePlanRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetEligebilityResponse getEligebility(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest getEligebilityRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCategoryResponse getCatMigration(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetCategoryRequest getCatMigrationRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.CheckRateplanResponse checkRateplan(com.billcom.apc.generatedSOAP.bscs.apcHandling.CheckRateplanRequest checkRateplanRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.PrixMigrationResponse getMigrationPrix(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMigrationRequest getMigrationPrixRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.ProrateResponse calculateProrata(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest calculateProrataRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.AddTicklerResponse addTickler(com.billcom.apc.generatedSOAP.bscs.apcHandling.AddTicklerRequest addTicklerRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.UserHasRightResponse userHasRight(com.billcom.apc.generatedSOAP.bscs.apcHandling.UserHasRightRequest userHasRightRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.UserGroupResponse userGroup(com.billcom.apc.generatedSOAP.bscs.apcHandling.UserGroupRequest userGroupRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse activateContract(com.billcom.apc.generatedSOAP.bscs.apcHandling.CoIdRequest activateContractRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.CreateContractResponse createContract(com.billcom.apc.generatedSOAP.bscs.apcHandling.CreateContractRequest createContractRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetDateFactureResponse getDateFacture(com.billcom.apc.generatedSOAP.bscs.apcHandling.CustomerRequest getDateFactureRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse addCugContract(com.billcom.apc.generatedSOAP.bscs.apcHandling.AddCugRequest addCugRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMigrationTypeResponse getMigrationtype(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetMigrationRequest getMigrationTypeRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse updateAdvCharge(com.billcom.apc.generatedSOAP.bscs.apcHandling.UpdateAdvChargeRequest updateAdvChargeRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetListTemplateRequestResponse getListTemplate(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetListTemplateRequest getListTemplateRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.OperationResponse insertApcCugHist(com.billcom.apc.generatedSOAP.bscs.apcHandling.ApcCugHistRequest apcCugHistRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
    public com.billcom.apc.generatedSOAP.bscs.apcHandling.GetConfigBalanceResponse getconfigBalance(com.billcom.apc.generatedSOAP.bscs.apcHandling.GetConfigBalanceRequest getconfigBalanceRequest) throws java.rmi.RemoteException, com.billcom.apc.generatedSOAP.bscs.apcHandling.UnexpectedErrorFault;
}
