package com.billcom.apc.ws.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-07-28T15:25:44.742+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://manager.ws.apc.billcom.com/", name = "APCManager")
@XmlSeeAlso({ObjectFactory.class})
public interface APCManager {

    @WebMethod
    @RequestWrapper(localName = "contractHasMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.ContractHasMigration")
    @ResponseWrapper(localName = "contractHasMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.ContractHasMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.VerifyMigrationResponse contractHasMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.VerifyMigrationRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendEmailMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.SendEmailMigration")
    @ResponseWrapper(localName = "sendEmailMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.SendEmailMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.SendEmailResponse sendEmailMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.SendMailRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getContractHistory", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetContractHistory")
    @ResponseWrapper(localName = "getContractHistoryResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetContractHistoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetMigrationsResponse getContractHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceBscs", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceBscs")
    @ResponseWrapper(localName = "adjustBalanceBscsResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceBscsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.AdjustBalanceResponse adjustBalanceBscs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMigrationOrderParentProcess", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationOrderParentProcess")
    @ResponseWrapper(localName = "getMigrationOrderParentProcessResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationOrderParentProcessResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetMigrationOrderParentResponse getMigrationOrderParentProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.OrderRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "percistMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.PercistMigration")
    @ResponseWrapper(localName = "percistMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.PercistMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.PercistMigrationOrderResponse percistMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.PercistMigrationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getNBofmigrationexecutedforcontract", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetNBofmigrationexecutedforcontract")
    @ResponseWrapper(localName = "getNBofmigrationexecutedforcontractResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetNBofmigrationexecutedforcontractResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.NbreMigrationExecutedResponse getNBofmigrationexecutedforcontract(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.NbreMigrationExecutedRequest arg0
    ) throws InvalidInputException_Exception, ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.UpdateMigration")
    @ResponseWrapper(localName = "updateMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.UpdateMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.UpdateMigrationOrderResponse updateMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.UpdateMigrationOrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.DeleteMigration")
    @ResponseWrapper(localName = "deleteMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.DeleteMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.DeleteMigrationOrderResponse deleteMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.OrderRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMigrationOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationOrder")
    @ResponseWrapper(localName = "getMigrationOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetMigrationResponse getMigrationOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.OrderRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getListOrderId", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetListOrderId")
    @ResponseWrapper(localName = "getListOrderIdResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetListOrderIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Long> getListOrderId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMigrationList", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationList")
    @ResponseWrapper(localName = "getMigrationListResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetMigrationListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetMigrationsResponse getMigrationList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.GetMigrationsRequest arg0
    ) throws InvalidInputException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateCoIdMigrationOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.UpdateCoIdMigrationOrder")
    @ResponseWrapper(localName = "updateCoIdMigrationOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.UpdateCoIdMigrationOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean updateCoIdMigrationOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.math.BigInteger arg2
    ) throws InvalidInputException_Exception, NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceMigration")
    @ResponseWrapper(localName = "adjustBalanceMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.AdjustBalanceResponse adjustBalanceMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDetailsOrder", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetDetailsOrder")
    @ResponseWrapper(localName = "getDetailsOrderResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetDetailsOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetOrderResponse getDetailsOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.OrderRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verifyFunctionalEligebility", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.VerifyFunctionalEligebility")
    @ResponseWrapper(localName = "verifyFunctionalEligebilityResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.VerifyFunctionalEligebilityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.VerifyEligebilityResponse verifyFunctionalEligebility(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.VerifyMigrationRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "adjustBalanceIn", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceIn")
    @ResponseWrapper(localName = "adjustBalanceInResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.AdjustBalanceInResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.AdjustBalanceResponse adjustBalanceIn(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.AdjustBalanceRequest arg0
    ) throws NotFoundException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getEligibileContractForMigration", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetEligibileContractForMigration")
    @ResponseWrapper(localName = "getEligibileContractForMigrationResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.GetEligibileContractForMigrationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.GetEligibleContractForMigrationResponse getEligibileContractForMigration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.GetEligibileContractForMigrationRequest arg0
    ) throws InvalidInputException_Exception, NotFoundException_Exception, ParseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verifyTechnicalEligibility", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.VerifyTechnicalEligibility")
    @ResponseWrapper(localName = "verifyTechnicalEligibilityResponse", targetNamespace = "http://manager.ws.apc.billcom.com/", className = "com.billcom.apc.ws.manager.VerifyTechnicalEligibilityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.billcom.apc.ws.manager.VerifyEligebilityResponse verifyTechnicalEligibility(
        @WebParam(name = "arg0", targetNamespace = "")
        com.billcom.apc.ws.manager.VerifyMigrationRequest arg0
    );
}
