
package com.billcom.apc.ws.manager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2021-07-28T15:25:44.737+01:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "ParseException", targetNamespace = "http://manager.ws.apc.billcom.com/")
public class ParseException_Exception extends Exception {
    
    private com.billcom.apc.ws.manager.ParseException parseException;

    public ParseException_Exception() {
        super();
    }
    
    public ParseException_Exception(String message) {
        super(message);
    }
    
    public ParseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParseException_Exception(String message, com.billcom.apc.ws.manager.ParseException parseException) {
        super(message);
        this.parseException = parseException;
    }

    public ParseException_Exception(String message, com.billcom.apc.ws.manager.ParseException parseException, Throwable cause) {
        super(message, cause);
        this.parseException = parseException;
    }

    public com.billcom.apc.ws.manager.ParseException getFaultInfo() {
        return this.parseException;
    }
}
